# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.1.12"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.1.12/cy_0.1.12_darwin_arm64.tar.gz"
      sha256 "8f239a91a5088299864fa5f66d9c6487476469dbbd6591bf51ac3b7afc3c0323"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.12/cy_0.1.12_darwin_amd64.tar.gz"
      sha256 "c178854bf5d574fcfc242feb9fa39429aeda56a31fc1513d20754dc49d93a3f9"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.12/cy_0.1.12_linux_amd64.tar.gz"
      sha256 "6879580855d4666801efafa3d8c685d38197bf2dc06fdc270e49cddcab1b9309"

      def install
        bin.install "cy"
      end
    end
  end
end
