# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.6.0/cy_0.6.0_darwin_arm64.tar.gz"
      sha256 "11b7a63dc044cbe1a2764a578b533459ffd297076468a486d07bbea526723b77"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.6.0/cy_0.6.0_darwin_amd64.tar.gz"
      sha256 "6a5c9cb10b5aa64b28c14bd3aa4a3fe6c8179f37a17091fff47058565caa3992"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.6.0/cy_0.6.0_linux_amd64.tar.gz"
      sha256 "7a002e938cd58b728439e8a6e61f0f0293f4e5e643a1483f90f4e38faa053627"

      def install
        bin.install "cy"
      end
    end
  end
end
