# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.10.1/cy_0.10.1_darwin_arm64.tar.gz"
      sha256 "1a4b7ee0eeb8db372ae06f8fd4c59fc7500826c32443fe745e07aee89e9884c8"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.10.1/cy_0.10.1_darwin_amd64.tar.gz"
      sha256 "451139c61232e755986b38dc20b77261a181266a136c9e1a8386baab2dac949f"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.10.1/cy_0.10.1_linux_amd64.tar.gz"
      sha256 "42bffec392bfa5831f6e73727b5a0c171459a163c7424a0e766a9117ff585f37"

      def install
        bin.install "cy"
      end
    end
  end
end
