# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.3.2/cy_0.3.2_darwin_arm64.tar.gz"
      sha256 "90b662f14b3e7edf76604029989384e0eb2f1516ea8659791336411fd78d9303"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.3.2/cy_0.3.2_darwin_amd64.tar.gz"
      sha256 "07efd0fcac5c0cd316a48043cb5547aad4121529e7f02bb80a0713db4d169b7f"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.3.2/cy_0.3.2_linux_amd64.tar.gz"
      sha256 "646b3db87dbeac37dcc65f14f83041c8c2b681c212e90aa2e2a9d5e03b1b9774"

      def install
        bin.install "cy"
      end
    end
  end
end
