# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.9.1/cy_0.9.1_darwin_arm64.tar.gz"
      sha256 "b3419a80d050cfc19ba93e626f14da17ee07debd524e1d237960bf5a7386b007"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.9.1/cy_0.9.1_darwin_amd64.tar.gz"
      sha256 "ec9fb5848d7329c04740c8bde8ba383e77daf6d6d7689199594639c06834f544"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.9.1/cy_0.9.1_linux_amd64.tar.gz"
      sha256 "c219eb157183281708a660f3e3721abeb98685f7623535fc866bc3ffad2780b7"

      def install
        bin.install "cy"
      end
    end
  end
end
