# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.10.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.10.3/cy_0.10.3_darwin_arm64.tar.gz"
      sha256 "39ffa56e9aeb2c70c18e20f263259f95b6cfb967c4326504f9d8f9a09569bd35"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.10.3/cy_0.10.3_darwin_amd64.tar.gz"
      sha256 "d45469925bcc2a12378408219607aa131078948d9efb4b133fb0a082bee26484"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.10.3/cy_0.10.3_linux_amd64.tar.gz"
      sha256 "febaeadb53c8cc06263434c0aa4edb7c5425dda39b01135bb9e63d664407ddba"

      def install
        bin.install "cy"
      end
    end
  end
end
