# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.12.0/cy_0.12.0_darwin_arm64.tar.gz"
      sha256 "5a6d7c7a46a9089213ab4bedc0da1d887c9a3578f9b00f04d562bd7d7ff68d5b"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.12.0/cy_0.12.0_darwin_amd64.tar.gz"
      sha256 "d426d357b8941535b94a6d9c4c434453e49ad47375aba141d4cc92d74e12dc4a"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.12.0/cy_0.12.0_linux_amd64.tar.gz"
      sha256 "7912c18a683430fedd47e3bbc960c7872651e5526c659524ae1f9c5cb65de047"

      def install
        bin.install "cy"
      end
    end
  end
end
