# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.8.0/cy_0.8.0_darwin_arm64.tar.gz"
      sha256 "61426b64a0034d57cdafef5e100551c5425f4fbeea2554a8e9ed291a94113c93"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.8.0/cy_0.8.0_darwin_amd64.tar.gz"
      sha256 "d23a696262fd6b7201b352a0e811510f74df22df8109e84f38cc9876029fc6ba"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.8.0/cy_0.8.0_linux_amd64.tar.gz"
      sha256 "f410127d519215b4373dfb71feee31f340f0af099307e115e3479c9bc338a2cd"

      def install
        bin.install "cy"
      end
    end
  end
end
