# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.2.8/cy_0.2.8_darwin_arm64.tar.gz"
      sha256 "3f73e691fbedf42971dbcc3e8a51c2349aa9dce1a40c895d5db530e6bfeacb2a"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.8/cy_0.2.8_darwin_amd64.tar.gz"
      sha256 "6e1fd5d5bb6864fe6b1ce33cd0695c1e5e26f743c2030b991c5deb744e0c43ac"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.8/cy_0.2.8_linux_amd64.tar.gz"
      sha256 "a9c7fa7733f4f79f37383a34213f866fc3e1a75a1cc4d35f77ca7657c374fb93"

      def install
        bin.install "cy"
      end
    end
  end
end
