# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.10.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.10.2/cy_0.10.2_darwin_arm64.tar.gz"
      sha256 "4b7e3b186a387fd8f3322f8589470c6fa6d394261d61784b64385b6307093b93"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.10.2/cy_0.10.2_darwin_amd64.tar.gz"
      sha256 "c85cdf9c43c71e2f41fb3b1712f6cf2023a0ac9ca4ba5c4d2354788e6a915d9e"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.10.2/cy_0.10.2_linux_amd64.tar.gz"
      sha256 "c6906a3777f326d8af964b91e36f80bb63f7fad80e6c8b3be0b24419ab29d144"

      def install
        bin.install "cy"
      end
    end
  end
end
