# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.1.13"
  license "MIT"
  
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.1.13/cy_0.1.13_darwin_arm64.tar.gz"
      sha256 "612634967ebc2513b5a7f558fa03e7921ab4a532475ee748a4fbd2477c40a694"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.13/cy_0.1.13_darwin_amd64.tar.gz"
      sha256 "4590ec9686fa8bef81beece324687ba19a64b398a693f381a06beb8becd9a35e"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.13/cy_0.1.13_linux_amd64.tar.gz"
      sha256 "f0209e3996c837683d1642fe7ef6585af0030d5efa365b65069ec105d3de5305"

      def install
        bin.install "cy"
      end
    end
  end
end
