# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.2.4/cy_0.2.4_darwin_arm64.tar.gz"
      sha256 "3bace62745db975ff84b898983dc59ad76b9011c13bcbc9264a07d73656a655b"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.4/cy_0.2.4_darwin_amd64.tar.gz"
      sha256 "5de53244834151c65d58063e4b853f74fc46f62998bbdabef981bad0498e67fe"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.4/cy_0.2.4_linux_amd64.tar.gz"
      sha256 "c1035599d87dcc080d142983a88d8bed7c44d6d1bb785dc55636a42a4d016293"

      def install
        bin.install "cy"
      end
    end
  end
end
