# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.5.0/cy_0.5.0_darwin_arm64.tar.gz"
      sha256 "a56af599f4ae5b3976d0719374b25ef6aec2344a0a5a61494279542f89281434"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.5.0/cy_0.5.0_darwin_amd64.tar.gz"
      sha256 "0598388e18f70d51fc4f50ed843e775378244f2119de02f55f5bc275ef35af43"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.5.0/cy_0.5.0_linux_amd64.tar.gz"
      sha256 "35c7a6b96c87ec2557919b823b120fcab6e8220702a20b2b5ef5e843415f3e5e"

      def install
        bin.install "cy"
      end
    end
  end
end
