# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.1.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.1.17/cy_0.1.17_darwin_arm64.tar.gz"
      sha256 "84bd35bc598739e1680fa4e210670fec78139ba6030f1bd67df1b65f3e2c9dd7"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.17/cy_0.1.17_darwin_amd64.tar.gz"
      sha256 "2a5972df8dd804411cc3ce2d7c11aa5683941808a20cfd170baf356c791cd86d"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.17/cy_0.1.17_linux_amd64.tar.gz"
      sha256 "6458fbb51895e9450e2b43ec11b64f37a11ee645658231da1de91e9054367cf6"

      def install
        bin.install "cy"
      end
    end
  end
end
