# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.2.1/cy_0.2.1_darwin_arm64.tar.gz"
      sha256 "41b42ad9e522eaac7e90a7c507158d8195025727888e54a055ac8f0e8e17011f"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.1/cy_0.2.1_darwin_amd64.tar.gz"
      sha256 "09c4ab785dd83b16cd101626939c8af6f7303d099d6208ff6997322470ad3a01"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.1/cy_0.2.1_linux_amd64.tar.gz"
      sha256 "6456ca1744cd89f8610f7f9d1dcc7422789048454c2809ade0cc5506060f8c0a"

      def install
        bin.install "cy"
      end
    end
  end
end
