# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.10.0/cy_0.10.0_darwin_arm64.tar.gz"
      sha256 "3d609bbb14af7bbb6f64b957ec9cc1aca7a9d513518e6e320342942953f2abf1"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.10.0/cy_0.10.0_darwin_amd64.tar.gz"
      sha256 "df2d1dcdc07272efb4e8007158bdae60c62e9f09e87309466c23c10fc7e46770"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.10.0/cy_0.10.0_linux_amd64.tar.gz"
      sha256 "92323323f45a294a32f663d210a0c64853057535ca5919a93f3ac6772b1fa9a8"

      def install
        bin.install "cy"
      end
    end
  end
end
