# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.4.0/cy_0.4.0_darwin_arm64.tar.gz"
      sha256 "3e0a80595d81efbeaedb0f99d5443c2a28462e681dfd67549ae10036c376820e"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.4.0/cy_0.4.0_darwin_amd64.tar.gz"
      sha256 "ba01a1b13043b83f59259f30e596d79c24ba9a72b449ffc8c4c9c1db3086e2c3"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.4.0/cy_0.4.0_linux_amd64.tar.gz"
      sha256 "03160e15e4f4ea2eff716cfa26f5c17d689a78988fb12116a137e6ed286cce84"

      def install
        bin.install "cy"
      end
    end
  end
end
