# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.1.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.1.14/cy_0.1.14_darwin_arm64.tar.gz"
      sha256 "387932a1d5c137443493d82f3591a6953b40dcb430a5972f098ed967eeda1cc0"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.14/cy_0.1.14_darwin_amd64.tar.gz"
      sha256 "233e6344d58077626e90a908b84367be9b9bdab103e29285ac4e3c122644dfa9"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.14/cy_0.1.14_linux_amd64.tar.gz"
      sha256 "8b39f8992735da4f57d4d71708451951e879ca6d379a7a7aca4f375acaafc91c"

      def install
        bin.install "cy"
      end
    end
  end
end
