# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.1.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.1.19/cy_0.1.19_darwin_arm64.tar.gz"
      sha256 "c3ecc3d9bc413c384db90539f1eac50f73c7e0f2970c0ca16163b163da99ccc3"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.19/cy_0.1.19_darwin_amd64.tar.gz"
      sha256 "da40a645ec19af1ad587c648a6e29d0a0d82cac550ec15c10f91fa86a2fca441"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.19/cy_0.1.19_linux_amd64.tar.gz"
      sha256 "2f505c6b14f2054a9cafa758a9e9fdf08f0df66d938eb8459b4a0cfbdb984100"

      def install
        bin.install "cy"
      end
    end
  end
end
