# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.9.2/cy_0.9.2_darwin_arm64.tar.gz"
      sha256 "78ea54fa1801e1ed0f3cfbe0f8389bff5b90c8be9a7ae2cf08fee6a913dd5f54"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.9.2/cy_0.9.2_darwin_amd64.tar.gz"
      sha256 "94b0477720cfdbd44999ce25fa63a72f1c7d8bbd43245464b6d783b72edaea8c"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.9.2/cy_0.9.2_linux_amd64.tar.gz"
      sha256 "05c6f84bd4394b1ea4d875e1381dfb62c473bcb9da0638af08bb05685e0214ff"

      def install
        bin.install "cy"
      end
    end
  end
end
