# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.7.0/cy_0.7.0_darwin_arm64.tar.gz"
      sha256 "1a69d127540c3db5ccbded21254e1318b13f52d7c7f55b059048de45af4ca819"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.7.0/cy_0.7.0_darwin_amd64.tar.gz"
      sha256 "abdf756513ede55e9c05cf4d220c2303819720812fe4acd05cdaa1ff52fe6418"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.7.0/cy_0.7.0_linux_amd64.tar.gz"
      sha256 "3d2e89f2d0b76b1de75748774056dff8ee4dfd2a31035d58936cbe6125f36016"

      def install
        bin.install "cy"
      end
    end
  end
end
