# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.2.5/cy_0.2.5_darwin_arm64.tar.gz"
      sha256 "5c36b50a7be1e7feafe362447d10b87345c51601fedb08bb567f6c53395e4fdb"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.5/cy_0.2.5_darwin_amd64.tar.gz"
      sha256 "69b1080fe7d6c5f7ef22731d30c9c29259168842fb888adcaf3450a5c7507e17"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.5/cy_0.2.5_linux_amd64.tar.gz"
      sha256 "3a21579c3c2e0e32cf8b70a3a6ab15764fefd148e8295e253b3f6deaaa777720"

      def install
        bin.install "cy"
      end
    end
  end
end
