# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.3.1/cy_0.3.1_darwin_arm64.tar.gz"
      sha256 "c1d74edaa4ac2e039345d5e65b213d22a687e6cd0f876b917c319fe8c7396049"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.3.1/cy_0.3.1_darwin_amd64.tar.gz"
      sha256 "6e064f4858f8d2b0f7df5de6bab28da6172c7096ba6b3e582b4628e110b3539d"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.3.1/cy_0.3.1_linux_amd64.tar.gz"
      sha256 "19a8260b50db76c752ae6bd8486b53c13096bdaa0fcb32302f44eb75e5f83328"

      def install
        bin.install "cy"
      end
    end
  end
end
