# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.2.2/cy_0.2.2_darwin_arm64.tar.gz"
      sha256 "1cbac8c663def500933a585371db3e76c8e85c3852471f127b74fb1ad6620523"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.2/cy_0.2.2_darwin_amd64.tar.gz"
      sha256 "deaa8969b9f71c04dd12867d335c1b8e294d824ade86c18ace6cc3e37d28edf6"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.2/cy_0.2.2_linux_amd64.tar.gz"
      sha256 "59a01289810777fb0f68590274c94722dedcff81b127710631662c145d542a74"

      def install
        bin.install "cy"
      end
    end
  end
end
