# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.9.0/cy_0.9.0_darwin_arm64.tar.gz"
      sha256 "953bf3023f451e52904d0282c4163b9b6c803011e751bea430b73c57baca5d9c"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.9.0/cy_0.9.0_darwin_amd64.tar.gz"
      sha256 "f06c1fe018c6a2387902b26c22de81a5e2ee16a349a2ed761cbf75b949de3aa4"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.9.0/cy_0.9.0_linux_amd64.tar.gz"
      sha256 "5f72258a459dfae8fa16a9d6cd26dd30c8921135a831f8927aafcc479ff4b369"

      def install
        bin.install "cy"
      end
    end
  end
end
