# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.1.8"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.1.8/cy_0.1.8_darwin_arm64.tar.gz"
      sha256 "2ebae0be6f7a32d8edd4fd8768f1ed627b324a08075d115944fb740164aeecfc"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.8/cy_0.1.8_darwin_amd64.tar.gz"
      sha256 "01eb1ec7eb1a81c9d9d125b989f98109e4a0f3b996d6893f4888987be939fff7"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.8/cy_0.1.8_linux_amd64.tar.gz"
      sha256 "0b2e66805836484fca2dde8a29c90a7fdf337bf293db55e5d71fe4edaea7a5ff"

      def install
        bin.install "cy"
      end
    end
  end
end
