# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.2.3/cy_0.2.3_darwin_arm64.tar.gz"
      sha256 "147907c1957746f4eb01e71e5f0c082f65ed126235f4c09d90225b8fab7d3622"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.3/cy_0.2.3_darwin_amd64.tar.gz"
      sha256 "e4cbca1df3fea6a0668102dfa7eb4154c532bf93054ef17c834d7e56302b6747"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.3/cy_0.2.3_linux_amd64.tar.gz"
      sha256 "e54324aecb8aae553bab1cc58b4c3c2a3b4f1af53d66207e6f4a6a8513541712"

      def install
        bin.install "cy"
      end
    end
  end
end
