# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.1.8"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.1.8/cy_0.1.8_darwin_arm64.tar.gz"
      sha256 "de52a07c288f4318aba8d4eae97512e5308b68dc489ae1d06f4993a6d43323eb"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.8/cy_0.1.8_darwin_amd64.tar.gz"
      sha256 "1781d8e758de47ae27bf3dd7ccb1587b2ef553193dddfb67a6e0535503e42fa8"

      def install
        bin.install "cy"
      end
    end
  end
