# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.1.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.1.16/cy_0.1.16_darwin_arm64.tar.gz"
      sha256 "67d0af07e271281d8aad23275ba91695fbbd9b04af3141cb6488deb50454974d"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.16/cy_0.1.16_darwin_amd64.tar.gz"
      sha256 "a40204e22b12330a84683308d99d947dbfddb257c01611a3dc8f2ffbe77b32c6"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.1.16/cy_0.1.16_linux_amd64.tar.gz"
      sha256 "8ba36bb81a38b0f600c0f2f24bdf40b859f2eb8cca20e25177bae0e31dd00b9e"

      def install
        bin.install "cy"
      end
    end
  end
end
