# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v0.2.0/cy_0.2.0_darwin_arm64.tar.gz"
      sha256 "644b5ccb783bf34628830acfddd3dc008befe6ee4eb4990a434d0ef1f44fb0e4"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.0/cy_0.2.0_darwin_amd64.tar.gz"
      sha256 "e802f4ec31a7ab56c80e0b5ca7af61561915a5960f26e657c29bdb44013f9f55"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v0.2.0/cy_0.2.0_linux_amd64.tar.gz"
      sha256 "af080f8e76fa83327c1d22dc90353c40224c0424252fc301d21f7b84f837d0df"

      def install
        bin.install "cy"
      end
    end
  end
end
