# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.3.0/cy_1.3.0_darwin_arm64.tar.gz"
      sha256 "6004c83e03f71e26b3ccd9c1dc7a5e68b383912809e0a54f6c695d4d83b5dee9"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.3.0/cy_1.3.0_darwin_amd64.tar.gz"
      sha256 "6c1e4799464e733f3b3ebf9ca37bf269aac1428f7c2bb924f9479fa1ec13bf71"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.3.0/cy_1.3.0_linux_amd64.tar.gz"
      sha256 "dec4102eb8f56f7a7257e157ccca4465085238c413649e1806020fc243016754"

      def install
        bin.install "cy"
      end
    end
  end
end
