# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.11.1/cy_1.11.1_darwin_arm64.tar.gz"
      sha256 "b85509e7b2b06ad621e5bda958984953c5fe8e6f58b79e13fb9c911e9f833919"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.11.1/cy_1.11.1_darwin_amd64.tar.gz"
      sha256 "8a65af9a8c206f7d06b20eae6c1cd590a92336cd57d1a0f1a4ceaf33beefee66"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.11.1/cy_1.11.1_linux_amd64.tar.gz"
      sha256 "96083a610a9a79fa24d5558f8c5ac83db7913bb777ab4c7b8d7a8db540b4c9ed"

      def install
        bin.install "cy"
      end
    end
  end
end
