# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.2.0/cy_1.2.0_darwin_arm64.tar.gz"
      sha256 "4cb55381b3e83504db51df3644312316e635b41ef3eaea74ba323a13189d9862"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.2.0/cy_1.2.0_darwin_amd64.tar.gz"
      sha256 "6e36f38bb687b200976658f8e5f69c6bdf284bcc83afc9b4989398e220823e7d"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.2.0/cy_1.2.0_linux_amd64.tar.gz"
      sha256 "7c08c4feb382deb399d6804ec9ae98c8dd11ecae1dc250458720daa2dad1b194"

      def install
        bin.install "cy"
      end
    end
  end
end
