# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.6.0/cy_1.6.0_darwin_arm64.tar.gz"
      sha256 "112236bb3a18a0c614bf917f0bf56f1c5e9ecef064da49a81844664f924b5251"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.6.0/cy_1.6.0_darwin_amd64.tar.gz"
      sha256 "75fd1d50afee749e7abfb0aa246058832ba5e9aac44ac57283cdfa90ab325968"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.6.0/cy_1.6.0_linux_amd64.tar.gz"
      sha256 "86d82dc6f0e9b3d1449949ffba7d951041de2268c797ad55a2f85472e117d238"

      def install
        bin.install "cy"
      end
    end
  end
end
