# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.5.1/cy_1.5.1_darwin_arm64.tar.gz"
      sha256 "5049eaa65334073875a61fc6bb41667591a7a7404a130e3db5be011e33955397"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.5.1/cy_1.5.1_darwin_amd64.tar.gz"
      sha256 "100e6cf7d3a191e147534143fa0091bd9d2f50dd44ee72330cbb1ef84a961db4"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.5.1/cy_1.5.1_linux_amd64.tar.gz"
      sha256 "6031b9ffbe8becee3543207f407bd4bcf7787f1c6e163cc55e826eb10652585e"

      def install
        bin.install "cy"
      end
    end
  end
end
