# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.10.0/cy_1.10.0_darwin_arm64.tar.gz"
      sha256 "7c25c167071464aef7edecf228391888aecfdc70e2b4bab2225109013cc310ca"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.10.0/cy_1.10.0_darwin_amd64.tar.gz"
      sha256 "31daf228481b79b971c7a498e15034b1e3d5854034dc1b1eb484e4554402a928"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.10.0/cy_1.10.0_linux_amd64.tar.gz"
      sha256 "7068454a14d0b67e88fb58c118013b0ef7d14c9ed898fcac66360427d7cadfd3"

      def install
        bin.install "cy"
      end
    end
  end
end
