# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.9.1/cy_1.9.1_darwin_arm64.tar.gz"
      sha256 "3ec494ec6d1d40efb1552e476998a6adf306c6d2f16f87d98f34c2e7fd84de59"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.9.1/cy_1.9.1_darwin_amd64.tar.gz"
      sha256 "bfa854719c39dbc2b6762c5a4fa444cb6a775d8282eafc4eb6a4592354e5349a"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.9.1/cy_1.9.1_linux_amd64.tar.gz"
      sha256 "b3a3fbbcd3436d7cc0ba738089395c75927afeb69ea346ccf6201b9f87ff5d1a"

      def install
        bin.install "cy"
      end
    end
  end
end
