# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.9.0/cy_1.9.0_darwin_arm64.tar.gz"
      sha256 "154adf4f013ba8a0176cbafd8183cc8d276327d1f6ac3a56a5f19cbf7bf64f21"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.9.0/cy_1.9.0_darwin_amd64.tar.gz"
      sha256 "2221cd3ad81df758637148419ae48065b8c6ab98156c75975f1fb64822be474e"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.9.0/cy_1.9.0_linux_amd64.tar.gz"
      sha256 "c0aa19665aa53f10511fac5029129e43aa3517559e387b21e962bef63fc03f1c"

      def install
        bin.install "cy"
      end
    end
  end
end
