# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.3.1/cy_1.3.1_darwin_arm64.tar.gz"
      sha256 "88c9e6407f52466da0b29c30cfa86e43c3673a83c81d86205c6ba8c0ed133742"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.3.1/cy_1.3.1_darwin_amd64.tar.gz"
      sha256 "cd2dccb47ef1143b33e4efb695a268d2c0d2d3eead9035139e11b580e73ab694"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.3.1/cy_1.3.1_linux_amd64.tar.gz"
      sha256 "4c9a2ae01def50ccd79ba807e3c305c799d4660998f0cd1dab334c45c7c07be6"

      def install
        bin.install "cy"
      end
    end
  end
end
