# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.7.1/cy_1.7.1_darwin_arm64.tar.gz"
      sha256 "5334a47b929cbc5981a625e2efa8a20e28f934bf7c7f563e30717f343369715f"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.7.1/cy_1.7.1_darwin_amd64.tar.gz"
      sha256 "69fcbf1ac0b7b693a1d95244a4d9dca5a986b17a0d11199584c3dc2a72dfa00c"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.7.1/cy_1.7.1_linux_amd64.tar.gz"
      sha256 "5a5976de7c6f948d68fd1efd334507d419bf3f394ab2fa7ff825c0340e90aceb"

      def install
        bin.install "cy"
      end
    end
  end
end
