# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.12.0/cy_1.12.0_darwin_arm64.tar.gz"
      sha256 "d88f3d907f1777385c7d83d028c9344919b3bb651c0f746db478388e6b76a085"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.12.0/cy_1.12.0_darwin_amd64.tar.gz"
      sha256 "7c880c9f85fef0fb63edcc87cf7a5cfbd69464d2c8aee055daf89976fce403f0"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.12.0/cy_1.12.0_linux_amd64.tar.gz"
      sha256 "6b3dc30cb53ecf72fe78d34f56d19af2303e056632a2eaf265b9058268f1ed42"

      def install
        bin.install "cy"
      end
    end
  end
end
