# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.11.0/cy_1.11.0_darwin_arm64.tar.gz"
      sha256 "1b69da0e6885ccecc21412c15ff172ebf1ee6a48fbf9fa571bc743a9d4d23237"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.11.0/cy_1.11.0_darwin_amd64.tar.gz"
      sha256 "cce56f905625dd31c8aa99bcaeecd30736274c416d1f7ba64242c8d4049604af"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.11.0/cy_1.11.0_linux_amd64.tar.gz"
      sha256 "84053a6f787510e005cc1d5a17b2d408e6f7bf721b6426bb3ef42282b9b28f9a"

      def install
        bin.install "cy"
      end
    end
  end
end
