# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.6.1/cy_1.6.1_darwin_arm64.tar.gz"
      sha256 "1651a9caa7e7d7b7e5e8801476e694c463dc257e16edea59e2a176195d5f576d"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.6.1/cy_1.6.1_darwin_amd64.tar.gz"
      sha256 "632ddd9be2e94c211c0f16544ef8fdd04fc2422c7a28731ddd6cb327d0f46934"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.6.1/cy_1.6.1_linux_amd64.tar.gz"
      sha256 "b1c21b7592c11f63ca19e3a815a60863441afb41115160a07208fc8d3af6a3bd"

      def install
        bin.install "cy"
      end
    end
  end
end
