# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.1.0/cy_1.1.0_darwin_arm64.tar.gz"
      sha256 "ac6cb8e978110c8291444546fe69f5d7e6d28bd6009b6d736d0b3e574e8d1648"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.1.0/cy_1.1.0_darwin_amd64.tar.gz"
      sha256 "4783b98dfbd26d0ab34bf30599515c1281491b1286d7f2f722323b1586328cd0"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.1.0/cy_1.1.0_linux_amd64.tar.gz"
      sha256 "e9310b3929fd3d067957a3e4a82a9d729a377fabbdc6dbe9efa06e00872e6a92"

      def install
        bin.install "cy"
      end
    end
  end
end
