# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.4.1/cy_1.4.1_darwin_arm64.tar.gz"
      sha256 "cb7e52e373e122bf8660de0e53291f274eb64174844b448a0a87581420131081"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.4.1/cy_1.4.1_darwin_amd64.tar.gz"
      sha256 "0ebfc01aca38992cfcdf79b21cb44f1a1fa76e40b77eb7f65298bee650310377"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.4.1/cy_1.4.1_linux_amd64.tar.gz"
      sha256 "f5aeab0852d516a6d412137ec023d48098e5c7f42a27b92a1f7dbc159b013707"

      def install
        bin.install "cy"
      end
    end
  end
end
