# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.5.0/cy_1.5.0_darwin_arm64.tar.gz"
      sha256 "be0773682f0cc8824a1095c45b7882c17b46616cc8675cada8f6053c915c0091"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.5.0/cy_1.5.0_darwin_amd64.tar.gz"
      sha256 "6e7b213d0bd9c2f7b4f242426e17e45f2a041e16f4ac9f1b07c7eccbbf3ed42f"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.5.0/cy_1.5.0_linux_amd64.tar.gz"
      sha256 "9ab95f81ed1acc760e19c9796c3374e11aefdbc3ef827d8b2a5725981b8e1c33"

      def install
        bin.install "cy"
      end
    end
  end
end
