# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.10.1/cy_1.10.1_darwin_arm64.tar.gz"
      sha256 "366d6056b44f28a24512a8509c47166cbba791491b59d2ab2b4c7328b988c715"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.10.1/cy_1.10.1_darwin_amd64.tar.gz"
      sha256 "7d0b36c73442c04bb181f90471b568f6f61b048741d4cc684d3527090ddaaa96"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.10.1/cy_1.10.1_linux_amd64.tar.gz"
      sha256 "84bbbb1881d9e68d2c0023d49f27882836a1c172b7b67268fd1525d81ae80ec8"

      def install
        bin.install "cy"
      end
    end
  end
end
