# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.7.0/cy_1.7.0_darwin_arm64.tar.gz"
      sha256 "dfd1ebc3d141649ed5fe239a1b2b0ba05379b878ae84e4304b0a5bb75f58dc9d"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.7.0/cy_1.7.0_darwin_amd64.tar.gz"
      sha256 "0f98d1a81d687048ee82af460144f9a296fe70c6ab3132a0851154b0dbe31aa1"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.7.0/cy_1.7.0_linux_amd64.tar.gz"
      sha256 "43d0fadb891631aee195b5c5af511bb103ad856f395f224e2b94a8753b5b49e3"

      def install
        bin.install "cy"
      end
    end
  end
end
