# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.12.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.12.1/cy_1.12.1_darwin_arm64.tar.gz"
      sha256 "3201ad98a09b581314611cb891192f216804f783d294d9087ae64fd51f7047d7"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.12.1/cy_1.12.1_darwin_amd64.tar.gz"
      sha256 "6f77d3f0424a31598ca5e42723cf8a919185f3d79a78af611b21bec5daa28c08"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.12.1/cy_1.12.1_linux_amd64.tar.gz"
      sha256 "d8ca301a7257052ca54f136f0461139e1390dfb110e14539b7054b6b47cc5a09"

      def install
        bin.install "cy"
      end
    end
  end
end
