# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cy < Formula
  desc "The time-traveling terminal multiplexer."
  homepage "https://github.com/cfoust/cy"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/cy/releases/download/v1.8.0/cy_1.8.0_darwin_arm64.tar.gz"
      sha256 "e96439e1e6b881ab7c8e8f8ac1bdc2817cea6786f70d63f991366351b9145272"

      def install
        bin.install "cy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.8.0/cy_1.8.0_darwin_amd64.tar.gz"
      sha256 "cab27f363c9ae958eb18184f012355ff0cc8293927e5792878f0cdac14fc3ad0"

      def install
        bin.install "cy"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/cy/releases/download/v1.8.0/cy_1.8.0_linux_amd64.tar.gz"
      sha256 "73a9848d94d06a0eb45f28f1518758e04bf2b0223abf4a977dd9170cff7ff014"

      def install
        bin.install "cy"
      end
    end
  end
end
