# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sour < Formula
  desc "A Sauerbraten server for the modern era."
  homepage "https://github.com/cfoust/sour"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/sour/releases/download/v0.2.4/sour_0.2.4_darwin_arm64.tar.gz"
      sha256 "bc475cabc8790504c7b4c75dd7cb88b1628aac1c826461bf663c2c7fd8680e05"

      def install
        bin.install "sour"
        pkgshare.install "assets/"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/sour/releases/download/v0.2.4/sour_0.2.4_linux_amd64.tar.gz"
      sha256 "cf07081ef23197704760ed1ba920e7465e6b6d4c18d7900bff0d0047b80f5783"

      def install
        bin.install "sour"
        pkgshare.install "assets/"
      end
    end
  end
end
