# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sour < Formula
  desc "A Sauerbraten server for the modern era."
  homepage "https://github.com/cfoust/sour"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/sour/releases/download/v0.2.0/sour_0.2.0_darwin_arm64.tar.gz"
      sha256 "a50e22f7636a1380c88ff2eed1db4fad6041ca5649e7aa8f3d22c08b3cc63567"

      def install
        bin.install "sour"
        pkgshare.install "assets/"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/sour/releases/download/v0.2.0/sour_0.2.0_linux_amd64.tar.gz"
      sha256 "579b02971c8cbc2f7d1cff9e8c8f13fb7b0f847a32fee834507443162ffd1e71"

      def install
        bin.install "sour"
        pkgshare.install "assets/"
      end
    end
  end
end
