# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sour < Formula
  desc "A Sauerbraten server for the modern era."
  homepage "https://github.com/cfoust/sour"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/sour/releases/download/v0.2.3/sour_0.2.3_darwin_arm64.tar.gz"
      sha256 "ffbd3a2d6073e72d81888c32e447b68bd46199c460564bfbad3f34d0df5f47c1"

      def install
        bin.install "sour"
        pkgshare.install "assets/"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/sour/releases/download/v0.2.3/sour_0.2.3_linux_amd64.tar.gz"
      sha256 "5c6872439d1bd427b1864408f8d77b5e788cee0afc33cc524a9b669a83f63a88"

      def install
        bin.install "sour"
        pkgshare.install "assets/"
      end
    end
  end
end
