# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sour < Formula
  desc "A Sauerbraten server for the modern era."
  homepage "https://github.com/cfoust/sour"
  version "0.1.2-next"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/sour/releases/download/v0.1.1/sour_0.1.2-next_darwin_arm64.tar.gz"
      sha256 "7ab706f13d17690a919f93deff905b3f9701885bd257ac4d3d192b37ad483094"

      def install
        bin.install "sour"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/sour/releases/download/v0.1.1/sour_0.1.2-next_linux_amd64.tar.gz"
      sha256 "0e07640d20d0dd623e28869050a6d5f4a2d0f15221f93e3beb1f6bb08dbb1406"

      def install
        bin.install "sour"
      end
    end
  end
end
