# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sour < Formula
  desc "A Sauerbraten server for the modern era."
  homepage "https://github.com/cfoust/sour"
  version "0.0.1-next"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/sour/releases/download/v0.0.0/sour_0.0.1-next_darwin_arm64.tar.gz"
      sha256 "3fdf26df72c982dc193051fb5f63320602c8a7c9198564633003fc258f4e090e"

      def install
        bin.install "sour"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/sour/releases/download/v0.0.0/sour_0.0.1-next_linux_amd64.tar.gz"
      sha256 "d1eede14755ef96d6ab62e465cd4409d4311c24b83dbc9692fad5a2fa0a742d5"

      def install
        bin.install "sour"
      end
    end
  end
end
