# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sour < Formula
  desc "A Sauerbraten server for the modern era."
  homepage "https://github.com/cfoust/sour"
  version "0.1.1-next"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/sour/releases/download/v0.1.0/sour_0.1.1-next_darwin_arm64.tar.gz"
      sha256 "e42de1adc40c0fab182f6985343115351ca046035b28dd191b7c5a386b0fcad2"

      def install
        bin.install "sour"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/sour/releases/download/v0.1.0/sour_0.1.1-next_linux_amd64.tar.gz"
      sha256 "b56c4c9149150afa2df6f93b5700a804b980a727384cafa64d8ea517827df65d"

      def install
        bin.install "sour"
      end
    end
  end
end
