# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sour < Formula
  desc "A Sauerbraten server for the modern era."
  homepage "https://github.com/cfoust/sour"
  version "0.1.3-next"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/sour/releases/download/v0.1.2/sour_0.1.3-next_darwin_arm64.tar.gz"
      sha256 "afab96e587d5a428d6c413371b067d187f1532fa13a128efbe5b367b045eba35"

      def install
        bin.install "sour"
        pkgshare.install "assets/"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/sour/releases/download/v0.1.2/sour_0.1.3-next_linux_amd64.tar.gz"
      sha256 "b08d9d0621afe8f53ee70e18fada9fb810cbc1e5bc11172c15ce9798db641f98"

      def install
        bin.install "sour"
        pkgshare.install "assets/"
      end
    end
  end
end
