# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sour < Formula
  desc "A Sauerbraten server for the modern era."
  homepage "https://github.com/cfoust/sour"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cfoust/sour/releases/download/v0.2.2/sour_0.2.2_darwin_arm64.tar.gz"
      sha256 "54a5df2c2a50732030ec09f08a0da8356f65c44141e895a2ea9e321188da8e0e"

      def install
        bin.install "sour"
        pkgshare.install "assets/"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cfoust/sour/releases/download/v0.2.2/sour_0.2.2_linux_amd64.tar.gz"
      sha256 "4de2b3fd15dc579a7017b9b21c654d79fe0078ebe3578a4f3998a8e34fdac889"

      def install
        bin.install "sour"
        pkgshare.install "assets/"
      end
    end
  end
end
